# Generated by Django 3.2.6 on 2021-08-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('acumulado_meses', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acumulado_ano', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
